---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.2
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.0.0"
